/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Lead {
    id: bigint;
    city: string;
    fullName: string;
    email: string;
    message: string;
    fundCategory: FundCategory;
    timestamp: bigint;
    phone: string;
    investmentRange: InvestmentRange;
}
export enum FundCategory {
    healthcare = "healthcare",
    realEstate = "realEstate",
    renewableEnergy = "renewableEnergy",
    infrastructure = "infrastructure",
    technology = "technology"
}
export enum InvestmentRange {
    range1 = "range1",
    range2 = "range2",
    range3 = "range3",
    range4 = "range4",
    range5 = "range5"
}
export interface backendInterface {
    getAllLeads(): Promise<Array<Lead>>;
    getFundCategoryStatistics(): Promise<Array<[FundCategory, bigint]>>;
    getInvestmentRangeStatistics(): Promise<Array<[InvestmentRange, bigint]>>;
    getLatestLeads(limit: bigint): Promise<Array<Lead>>;
    getLeadById(id: bigint): Promise<Lead>;
    getLeadCount(): Promise<bigint>;
    getLeadsByCity(city: string): Promise<Array<Lead>>;
    getLeadsByFundCategory(fundCategory: FundCategory): Promise<Array<Lead>>;
    submitLead(fullName: string, email: string, phone: string, city: string, fundCategory: FundCategory, investmentRange: InvestmentRange, message: string): Promise<{
        id: bigint;
        timestamp: bigint;
    }>;
}
import type { FundCategory as _FundCategory, InvestmentRange as _InvestmentRange, Lead as _Lead } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeads();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeads();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFundCategoryStatistics(): Promise<Array<[FundCategory, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFundCategoryStatistics();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFundCategoryStatistics();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvestmentRangeStatistics(): Promise<Array<[InvestmentRange, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvestmentRangeStatistics();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvestmentRangeStatistics();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestLeads(arg0: bigint): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestLeads(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestLeads(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadById(arg0: bigint): Promise<Lead> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadById(arg0);
                return from_candid_Lead_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadById(arg0);
            return from_candid_Lead_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadCount();
            return result;
        }
    }
    async getLeadsByCity(arg0: string): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByCity(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByCity(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsByFundCategory(arg0: FundCategory): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByFundCategory(to_candid_FundCategory_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByFundCategory(to_candid_FundCategory_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitLead(arg0: string, arg1: string, arg2: string, arg3: string, arg4: FundCategory, arg5: InvestmentRange, arg6: string): Promise<{
        id: bigint;
        timestamp: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLead(arg0, arg1, arg2, arg3, to_candid_FundCategory_n12(this._uploadFile, this._downloadFile, arg4), to_candid_InvestmentRange_n14(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLead(arg0, arg1, arg2, arg3, to_candid_FundCategory_n12(this._uploadFile, this._downloadFile, arg4), to_candid_InvestmentRange_n14(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
}
function from_candid_FundCategory_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FundCategory): FundCategory {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_InvestmentRange_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvestmentRange): InvestmentRange {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    city: string;
    fullName: string;
    email: string;
    message: string;
    fundCategory: _FundCategory;
    timestamp: bigint;
    phone: string;
    investmentRange: _InvestmentRange;
}): {
    id: bigint;
    city: string;
    fullName: string;
    email: string;
    message: string;
    fundCategory: FundCategory;
    timestamp: bigint;
    phone: string;
    investmentRange: InvestmentRange;
} {
    return {
        id: value.id,
        city: value.city,
        fullName: value.fullName,
        email: value.email,
        message: value.message,
        fundCategory: from_candid_FundCategory_n4(_uploadFile, _downloadFile, value.fundCategory),
        timestamp: value.timestamp,
        phone: value.phone,
        investmentRange: from_candid_InvestmentRange_n6(_uploadFile, _downloadFile, value.investmentRange)
    };
}
function from_candid_tuple_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_InvestmentRange, bigint]): [InvestmentRange, bigint] {
    return [
        from_candid_InvestmentRange_n6(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_tuple_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_FundCategory, bigint]): [FundCategory, bigint] {
    return [
        from_candid_FundCategory_n4(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    healthcare: null;
} | {
    realEstate: null;
} | {
    renewableEnergy: null;
} | {
    infrastructure: null;
} | {
    technology: null;
}): FundCategory {
    return "healthcare" in value ? FundCategory.healthcare : "realEstate" in value ? FundCategory.realEstate : "renewableEnergy" in value ? FundCategory.renewableEnergy : "infrastructure" in value ? FundCategory.infrastructure : "technology" in value ? FundCategory.technology : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    range1: null;
} | {
    range2: null;
} | {
    range3: null;
} | {
    range4: null;
} | {
    range5: null;
}): InvestmentRange {
    return "range1" in value ? InvestmentRange.range1 : "range2" in value ? InvestmentRange.range2 : "range3" in value ? InvestmentRange.range3 : "range4" in value ? InvestmentRange.range4 : "range5" in value ? InvestmentRange.range5 : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_InvestmentRange, bigint]>): Array<[InvestmentRange, bigint]> {
    return value.map((x)=>from_candid_tuple_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_FundCategory, bigint]>): Array<[FundCategory, bigint]> {
    return value.map((x)=>from_candid_tuple_n9(_uploadFile, _downloadFile, x));
}
function to_candid_FundCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FundCategory): _FundCategory {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_InvestmentRange_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvestmentRange): _InvestmentRange {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FundCategory): {
    healthcare: null;
} | {
    realEstate: null;
} | {
    renewableEnergy: null;
} | {
    infrastructure: null;
} | {
    technology: null;
} {
    return value == FundCategory.healthcare ? {
        healthcare: null
    } : value == FundCategory.realEstate ? {
        realEstate: null
    } : value == FundCategory.renewableEnergy ? {
        renewableEnergy: null
    } : value == FundCategory.infrastructure ? {
        infrastructure: null
    } : value == FundCategory.technology ? {
        technology: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvestmentRange): {
    range1: null;
} | {
    range2: null;
} | {
    range3: null;
} | {
    range4: null;
} | {
    range5: null;
} {
    return value == InvestmentRange.range1 ? {
        range1: null
    } : value == InvestmentRange.range2 ? {
        range2: null
    } : value == InvestmentRange.range3 ? {
        range3: null
    } : value == InvestmentRange.range4 ? {
        range4: null
    } : value == InvestmentRange.range5 ? {
        range5: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
