/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type FundCategory = { 'healthcare' : null } |
  { 'realEstate' : null } |
  { 'renewableEnergy' : null } |
  { 'infrastructure' : null } |
  { 'technology' : null };
export type InvestmentRange = { 'range1' : null } |
  { 'range2' : null } |
  { 'range3' : null } |
  { 'range4' : null } |
  { 'range5' : null };
export interface Lead {
  'id' : bigint,
  'city' : string,
  'fullName' : string,
  'email' : string,
  'message' : string,
  'fundCategory' : FundCategory,
  'timestamp' : bigint,
  'phone' : string,
  'investmentRange' : InvestmentRange,
}
export interface _SERVICE {
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getFundCategoryStatistics' : ActorMethod<[], Array<[FundCategory, bigint]>>,
  'getInvestmentRangeStatistics' : ActorMethod<
    [],
    Array<[InvestmentRange, bigint]>
  >,
  'getLatestLeads' : ActorMethod<[bigint], Array<Lead>>,
  'getLeadById' : ActorMethod<[bigint], Lead>,
  'getLeadCount' : ActorMethod<[], bigint>,
  'getLeadsByCity' : ActorMethod<[string], Array<Lead>>,
  'getLeadsByFundCategory' : ActorMethod<[FundCategory], Array<Lead>>,
  'submitLead' : ActorMethod<
    [string, string, string, string, FundCategory, InvestmentRange, string],
    { 'id' : bigint, 'timestamp' : bigint }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];