/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FundCategory = IDL.Variant({
  'healthcare' : IDL.Null,
  'realEstate' : IDL.Null,
  'renewableEnergy' : IDL.Null,
  'infrastructure' : IDL.Null,
  'technology' : IDL.Null,
});
export const InvestmentRange = IDL.Variant({
  'range1' : IDL.Null,
  'range2' : IDL.Null,
  'range3' : IDL.Null,
  'range4' : IDL.Null,
  'range5' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'fundCategory' : FundCategory,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'investmentRange' : InvestmentRange,
});

export const idlService = IDL.Service({
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getFundCategoryStatistics' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(FundCategory, IDL.Nat))],
      ['query'],
    ),
  'getInvestmentRangeStatistics' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(InvestmentRange, IDL.Nat))],
      ['query'],
    ),
  'getLatestLeads' : IDL.Func([IDL.Nat], [IDL.Vec(Lead)], ['query']),
  'getLeadById' : IDL.Func([IDL.Nat], [Lead], ['query']),
  'getLeadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getLeadsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
  'getLeadsByFundCategory' : IDL.Func(
      [FundCategory],
      [IDL.Vec(Lead)],
      ['query'],
    ),
  'submitLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        FundCategory,
        InvestmentRange,
        IDL.Text,
      ],
      [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : IDL.Int })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FundCategory = IDL.Variant({
    'healthcare' : IDL.Null,
    'realEstate' : IDL.Null,
    'renewableEnergy' : IDL.Null,
    'infrastructure' : IDL.Null,
    'technology' : IDL.Null,
  });
  const InvestmentRange = IDL.Variant({
    'range1' : IDL.Null,
    'range2' : IDL.Null,
    'range3' : IDL.Null,
    'range4' : IDL.Null,
    'range5' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'fundCategory' : FundCategory,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'investmentRange' : InvestmentRange,
  });
  
  return IDL.Service({
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getFundCategoryStatistics' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(FundCategory, IDL.Nat))],
        ['query'],
      ),
    'getInvestmentRangeStatistics' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(InvestmentRange, IDL.Nat))],
        ['query'],
      ),
    'getLatestLeads' : IDL.Func([IDL.Nat], [IDL.Vec(Lead)], ['query']),
    'getLeadById' : IDL.Func([IDL.Nat], [Lead], ['query']),
    'getLeadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getLeadsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
    'getLeadsByFundCategory' : IDL.Func(
        [FundCategory],
        [IDL.Vec(Lead)],
        ['query'],
      ),
    'submitLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          FundCategory,
          InvestmentRange,
          IDL.Text,
        ],
        [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : IDL.Int })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };